[versions]
# 依赖版本号
activityCompose = "1.8.2"
agp = "8.2.2"
ahoCorasickDoubleArrayTrie = "1.2.3"
annotation = "1.7.1"
apiVersion = "13.1.5"
appcompat = "1.6.1"
byteBuddyAndroid = "1.12.7"
datastorePreferences = "1.1.0-beta01"
desugar_jdk_libs = "2.0.4"
ezxhelper = "1.0.3"
api = "82"
flatbuffersJava = "23.5.26"
kaml = "0.55.0"
hutoolCore = "5.8.0.M1"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.16"
hilt = "2.50"
compose = "1.6.0-rc01"
kotlinxSerializationJson = "1.6.2"
lifecycle= "2.7.0"
okhttp = "4.12.0"
navigationCompose = "2.7.6"
protoc = "3.25.1"
protobufKotlinLite = "3.25.1"
multidex = "2.0.1"
provider = "13.1.5"
systemExtension = "1.0.1"
window-size = "1.2.0-beta02"

# @keep
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
buildTool = "34.0.0"
ndk = "25.0.8775105"

compose-compiler = "1.5.8"

jvm-target = "11"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

[libraries]

# compose
aho-corasick-double-array-trie = { module = "com.hankcs:aho-corasick-double-array-trie", version.ref = "ahoCorasickDoubleArrayTrie" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
byte-buddy-android = { module = "net.bytebuddy:byte-buddy-android", version.ref = "byteBuddyAndroid" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
flatbuffers-java = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffersJava" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
hutool-core = { module = "cn.hutool:hutool-core", version.ref = "hutoolCore" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
ezxhelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezxhelper" }
api = { module = "de.robv.android.xposed:api", version.ref = "api" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
provider = { module = "dev.rikka.shizuku:provider", version.ref = "provider" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "apiVersion" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

androidx-compose-animation = { module = "androidx.compose.animation:animation",version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation",version.ref = "compose" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material" , version.ref = "compose"}
androidx-compose-materialWindow = { module = "androidx.compose.material3:material3-window-size-class", version.ref="window-size" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime",version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling",version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose"  }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
system-extension = { module = "com.highcapable.betterandroid:system-extension", version.ref = "systemExtension" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }